// NOTE This file is auto-generated by Contentlayer

import type { Markdown, MDX, ImageFieldData, IsoDateTimeString } from 'contentlayer/core'
import * as Local from 'contentlayer/source-files'

export { isType } from 'contentlayer/client'

export type { Markdown, MDX, ImageFieldData, IsoDateTimeString }

/** Document types */
export type Article = {
  /** File path relative to `contentDirPath` */
  _id: string
  _raw: Local.RawDocumentData
  type: 'Article'
  listingPage: boolean
  slug?: string | undefined
  path?: string | undefined
  name: string
  description: string
  url?: string | undefined
  identifier: string
  image?: any | undefined
  sameAs?: string | undefined
  author?: string | undefined
  headline?: string | undefined
  dateCreated: IsoDateTimeString
  dateModified?: IsoDateTimeString | undefined
  datePublished?: IsoDateTimeString | undefined
  isPartOf?: string | undefined
  inLanguage?: string | undefined
  keywords?: string[] | undefined
  /** MDX file body */
  body: MDX
  collection: string
}

export type Page = {
  /** File path relative to `contentDirPath` */
  _id: string
  _raw: Local.RawDocumentData
  type: 'Page'
  listingPage: boolean
  slug?: string | undefined
  path?: string | undefined
  name: string
  description: string
  url?: string | undefined
  identifier: string
  image?: any | undefined
  sameAs?: string | undefined
  author?: string | undefined
  headline?: string | undefined
  dateCreated: IsoDateTimeString
  dateModified?: IsoDateTimeString | undefined
  datePublished?: IsoDateTimeString | undefined
  isPartOf?: string | undefined
  inLanguage?: string | undefined
  keywords?: string[] | undefined
  /** MDX file body */
  body: MDX
  collection: string
}

export type Person = {
  /** File path relative to `contentDirPath` */
  _id: string
  _raw: Local.RawDocumentData
  type: 'Person'
  listingPage: boolean
  slug?: string | undefined
  path?: string | undefined
  name: string
  description: string
  url?: string | undefined
  identifier: string
  image?: any | undefined
  sameAs?: string | undefined
  additionalName?: string | undefined
  email?: string | undefined
  familyName?: string | undefined
  givenName?: string | undefined
  jobTitle?: string | undefined
  telephone?: string | undefined
  /** MDX file body */
  body: MDX
  collection: string
}

/** Nested types */


/** Helper types */

export type AllTypes = DocumentTypes | NestedTypes
export type AllTypeNames = DocumentTypeNames | NestedTypeNames

export type DocumentTypes = Article | Page | Person
export type DocumentTypeNames = 'Article' | 'Page' | 'Person'

export type NestedTypes = never
export type NestedTypeNames = never

export type DataExports = {
  allDocuments: DocumentTypes[]
  allArticles: Article[]
  allPages: Page[]
  allPeople: Person[]
}
