name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FORCE_COLOR: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint Packages
        run: pnpm run lint

      - name: Test Packages
        run: pnpm run test

      - name: Build Packages
        run: pnpm run build

  build-examples:
    runs-on: ubuntu-latest

    needs: ci

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Contentlayer example
        working-directory: examples/contentlayer
        run: npm install

      - name: Install Astro example
        working-directory: examples/astro
        run: npm install

      - name: Install dependencies
        run: pnpm install

      - name: Test Build Astro example
        run: npx turbo astro-example:build
